create database dataunload
create schema external_stages


to move data from snowflake to s3

create table customers as
(select * from snowpipe.testcase.customers )

select * from DATAUNLOAD.EXTERNAL_STAGES.customers

CREATE STORAGE INTEGRATION UNLOADDATATOS3
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = 'S3'
ENABLED = TRUE 
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::136889125076:role/snowflaketos3'
STORAGE_ALLOWED_LOCATIONS = ('s3://dataunloadingtos3/csv/')

DESCRIBE STORAGE INTEGRATION UNLOADDATATOS3

CREATE OR REPLACE FILE FORMAT DATAUNLOAD.EXTERNAL_STAGES.CSV_FORMAT
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    COMPRESSION = 'NONE'
    SKIP_HEADER = 1
    NULL_IF = ('', 'NULL')
    EMPTY_FIELD_AS_NULL = TRUE;

COPY INTO 's3://dataunloadingtos3/csv/customers.csv'
FROM (SELECT CUSTOMER_ID, SUBSCRIPTION_DATE FROM DATAUNLOAD.EXTERNAL_STAGES.customers)
STORAGE_INTEGRATION = UNLOADDATATOS3
FILE_FORMAT = (FORMAT_NAME = 'DATAUNLOAD.EXTERNAL_STAGES.CSV_FORMAT')
HEADER = TRUE
OVERWRITE = TRUE
SINGLE = TRUE


